#pragma once

// Available system properties

// #define HAVE_AES128
#define HAVE_BTSTACK_STDIN
#define HAVE_LWIP
// #define HAVE_MALLOC
// #define HAVE_MBEDTLD_ECC_P256

// Embedded platform properties
#define HAVE_EMBEDDED_TIME_MS
// #define HAVE_EMBEDDED_TICK
// #define HAVE_HAL_AUDIO
// #define HAVE_HAL_AUDIO_SINK_STEREO_ONLY

// FreeRTOS platform properties
// #define HAVE_FREERTOS_INCLUDE_PREFIX

// POSIX platform properties
// #define HAVE_POSIX_FILE_IO
// #define HAVE_POSIX_TIME
// #define LINK_KEY_PATH
// #define LE_DEVICE_DB_PATH

// BTstack properties
// #define ENABLE_CLASSIC
#define ENABLE_BLE
// #define ENABLE_EHCILL
// #define ENABLE_H5
#define ENABLE_LOG_DEBUG
#define ENABLE_LOG_ERROR
#define ENABLE_LOG_INFO
#define ENABLE_SCO_OVER_HCI
// #define ENABLE_SCO_OVER_PCM
// #define ENABLE_HFP_WIDE_BAND_SPEECH
// #define ENABLE_HFP_AT_MESSAGES
#define ENABLE_LE_PERIPHERAL
#define ENABLE_LE_CENTRAL
// #define ENABLE_LE_SECURE_CONNECTIONS
// #define ENABLE_LE_PROACTIVE_AUTHENTICATION
// #define ENABLE_GATT_CLIENT_PAIRING
// #define ENABLE_MICRO_ECC_FOR_LE_SECURE_CONNECTIONS
// #define ENABLE_LE_DATA_LENGTH_EXTENSION
// #define ENABLE_LE_EXTENDED_ADVERTISING
// #define ENABLE_LE_PERIODIC_ADVERTISING
// #define ENABLE_LE_SIGNED_WRITE
// #define ENABLE_LE_PRIVACY_ADDRESS_RESOLUTION
// #define ENABLE_CROSS_TRANSPORT_KEY_DERIVATION
// #define ENABLE_L2CAP_ENHANCED_RETRANSMISSION_MODE
#define ENABLE_L2CAP_LE_CREDIT_BASED_FLOW_CONTROL_MODE
// #define ENABLE_L2CAP_ENHANCED_CREDIT_BASED_FLOW_CONTROL_MODE
#define ENABLE_HCI_CONTROLLER_TO_HOST_FLOW_CONTROL
// #define ENABLE_HCI_SERIALIZED_CONTROLLER_OPERATIONS
// #define ENABLE_ATT_DELAYED_RESPONSE
// #define ENABLE_BCM_PCM_WBS
// #define ENABLE_CC256X_ASSISTED_HFP
// #define ENABLE_RTK_PCM_WBS
// #define ENABLE_CC256X_BAUDRATE_CHANGE_FLOWCONTROL_BUG_WORKAROUND
// #define ENABLE_CYPRESS_BAUDRATE_CHANGE_FLOWCONTROL_BUG_WORKAROUND
// #define ENABLE_LE_LIMIT_ACL_FRAGMENT_BY_MAX_OCTETS
// #define ENABLE_TLV_FLASH_EXPLICIT_DELETE_FIELD
// #define ENABLE_TLV_FLASH_WRITE_ONCE
// #define ENABLE_CONTROLLER_WARM_BOOT
// #define ENABLE_SEGGER_RTT
// #define ENABLE_EXPLICIT_CONNECTABLE_MODE_CONTROL
// #define ENABLE_EXPLICIT_IO_CAPABILITIES_REPLY
// #define ENABLE_EXPLICIT_LINK_KEY_REPLY
// #define ENABLE_EXPLICIT_BR_EDR_SECURITY_MANAGER
// #define ENABLE_EXPLICIT_DEDICATED_BONDING_DISCONNNECT
// #define ENABLE_CLASSIC_OOB_PAIRING
// #define ENABLE_A2DP_EXPLICIT_CONFIG
// #define ENABLE_AVDTP_ACCEPTOR_EXPLICIT_START_STREAM_CONFIRMATION
// #define ENABLE_LE_WHITELIST_TOUCH_AFTER_RESOLVING_LIST_UPDATE
// #define ENABLE_LE_SET_ADV_PARAMS_ON_RANDOM_ADDRESS_CHANGE
// #define ENABLE_CONTROLLER_DUMP_PACKETS

// HCI Controller to Host Flow Control
#define HCI_HOST_ACL_PACKET_NUM 3
#define HCI_HOST_ACL_PACKET_LEN 1024
#define HCI_HOST_SCO_PACKET_NUM 120
#define HCI_HOST_SCO_PACKET_LEN 3

// Memory configuration directives
#define HCI_ACL_PAYLOAD_SIZE (1691 + 4)
#define HCI_ACL_CHUNK_SIZE_ALIGNMENT 4
#define HCI_INCOMING_PRE_BUFFER_SIZE 14
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define MAX_NR_BNEP_CHANNELS 1
#define MAX_NR_BNEP_SERVICES 1
#define MAX_NR_BTSTACK_LINK_KEY_DB_MEMORY_ENTRIES 2
#define MAX_NR_GATT_CLIENTS 1
#define MAX_NR_HCI_CONNECTIONS 2
#define MAX_NR_HFP_CONNECTIONS 1
#define MAX_NR_L2CAP_CHANNELS 4
#define MAX_NR_L2CAP_SERVICES 3
#define MAX_NR_RFCOMM_CHANNELS 1
#define MAX_NR_RFCOMM_MULTIPLEXERS 1
#define MAX_NR_RFCOMM_SERVICES 1
#define MAX_NR_SERVICE_RECORD_ITEMS 4
#define MAX_NR_SM_LOOKUP_ENTRIES 3
#define MAX_NR_WHITELIST_ENTRIES 16
#define MAX_NR_LE_DEVICE_DB_ENTRIES 16

// Non-volatile memory directives
#define NVM_NUM_LINK_KEYS 16
#define NVM_NUM_DEVICE_DB_ENTRIES 16
// #define NVM_NUM_GATT_SERVER_CCC 1

// HCI Dump Stdout directives
// #define HCI_DUMP_STDOUT_MAX_SIZE_ACL 0
// #define HCI_DUMP_STDOUT_MAX_SIZE_SCO 0
// #define HCI_DUMP_STDOUT_MAX_SIZE_ISO 0

// SEGGER Real Time Transfer (RTT) directives
// #define SEGGER_RTT_PACKETLOG_MODE SEGGER_RTT_MODE_NO_BLOCK_SKIP
// #define SEGGER_RTT_PACKETLOG_CHANNEL 0
// #define SEGGER_RTT_PACKETLOG_BUFFER_SIZE 1024
