USB_VID = 0x239A
USB_PID = 0x8120
USB_PRODUCT = "Pico RM2"
USB_MANUFACTURER = "Raspberry Pi"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"

CIRCUITPY_USB_HOST = 0

CIRCUITPY__EVE = 1

CIRCUITPY_CYW43_RM2 = 1
CIRCUITPY_SSL = 1
CIRCUITPY_HASHLIB = 1
CIRCUITPY_WEB_WORKFLOW = 1
CIRCUITPY_MDNS = 1
CIRCUITPY_SOCKETPOOL = 1
CIRCUITPY_WIFI = 1


CFLAGS += \
    -DCYW43_PIN_WL_DYNAMIC=0 \
	-DCYW43_DEFAULT_PIN_WL_HOST_WAKE=10 \
	-DCYW43_DEFAULT_PIN_WL_REG_ON=13 \
	-DCYW43_DEFAULT_PIN_WL_CLOCK=12 \
	-DCYW43_DEFAULT_PIN_WL_DATA_IN=10 \
	-DCYW43_DEFAULT_PIN_WL_DATA_OUT=10 \
	-DCYW43_DEFAULT_PIN_WL_CS=11 \
	-DCYW43_WL_GPIO_COUNT=3 \
	-DCYW43_WL_GPIO_LED_PIN=0 \
	-DCYW43_PIO_CLOCK_DIV_INT=5 \
	-DCYW43_PIO_CLOCK_DIV_FRAC=0 \
	-DCYW43_SPI_PROGRAM_NAME="spi_gap0_sample1"

# Must be accompanied by a linker script change
CFLAGS += -DCIRCUITPY_FIRMWARE_SIZE='(1536 * 1024)'
